name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Python code
        run: pip install flake8 && flake8 .

      - name: Security Scan
        run: 
            pip install bandit
            bandit -r .

      - name: Build Packer
        run: packer build -var-file=vars.json packer.json

      - name: Push Docker Image to Docker hub
        if: success() && env.LINTER_SUCCESS == 'true' && env.SECURITY_SCAN_SUCCESS == 'true'
        run:
            echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
            docker load -i ./output/voting-app-docker-image.tar
            docker tag <your-image-id> your_username/voting-app:latest
            docker push your_username/voting-app:latest
